### ISSUE TITLE
Increase navigability by adding links within about.md

### ISSUE THREAD

**Issue by e-lo** [MobilityData/GTFS_Realtime_Best-Practices#10]
[about.md ](https://github.com/MobilityData/GTFS_Realtime_Best-Practices/blob/master/en/about.md) self-specifies that it should be linked to when referencing the GTFS Best Practices. However, it does not provide immediate transparency or understanding of how to navigate/find them within the repository.

Suggest adding a TOC-style set of links at the bottom to all other files in the repo.

**Comment by barbeau** [comment]
@e-lo I agree that navigation between pages can definitely be improved.

@MobilityData/transit-specs Could you share more on the plans for this content? Will it be automatically processed and posted at https://gtfs.mobilitydata.org/ or https://gtfs.org/, similar to the Schedule Best Practices?

**Comment by Cristhian-HA** [comment]
Hi @e-lo thanks for flagging this issue, we will add this suggestion to our workload and will integrate it in our next planning session in a couple of weeks from now.

**Comment by sccmcca** [comment]
+1 for adding a TOC

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
