### ISSUE TITLE
suggestion: serve GTFS-RT feeds with CORS enabled

### ISSUE THREAD

**Issue by derhuerst** [MobilityData/GTFS_Realtime_Best-Practices#16]
From my experience, almost all GTFS-Realtime feeds provided are intended for consumption by the public (or at least by unknown third parties). For web-based consumers to consume any of these feeds, Cross-Origin Resource Sharing (CORS) must be enabled; For more information, check out the [*enable CORS* website](https://enable-cors.org/) and the [CORS MDN page](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

> CORS introduces a standard mechanism that can be used by all browsers for implementing cross-domain requests. The spec defines a set of headers that allow the browser and server to communicate about which requests are (and are not) allowed. CORS continues the spirit of the open web by bringing API access to all.

Having web-based access to GTFS-RT feeds will drive innovation in the GTFS and transit space: Apps similar to [DC Metro Hero](https://www.dcmetrohero.com/) and development/debugging tools like [gtfs-rt-inspector](https://github.com/public-transport/gtfs-rt-inspector/blob/main/readme.md) & [TransitTracker](https://www.transittracker.ca) will be able to use the data directly.

**I therefore propose to add a best practice to add `*` (enabled for all origins) CORS headers.**

Answers to some common objections:

- Access control, e.g. using a static auth token, is of course still possible.
- excessive traffic usage – A `*` CORS header allows *any* browser visiting *any* website to fetch the GTFS-RT feed, and therefore enables many more devices to fetch the feed. This has been possible before as well, e.g. using the `<object>` tag. A better mechanism to prevent this is strict [rate limiting](https://www.keycdn.com/support/rate-limiting).

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
