### ISSUE TITLE
[Formatting] Consolidate Best Practices into single legible document

### ISSUE THREAD

**Issue by sccmcca** [MobilityData/GTFS_Realtime_Best-Practices#18]
Currently each section of the Best Practices is fragmented into its own markdown file. This makes the Best Practices hard to read as a stand-alone body of work.

**Comment by sccmcca** [comment]
Additionally, remove empty entries until a Best Practice is proposed for that field.

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
