### ISSUE TITLE
Best Practices suggestions

### ISSUE THREAD

**Issue by doconnoronca** [MobilityData/GTFS_Realtime_Best-Practices#2]
I'm Darwin O'Connor maker of the TransSee real time transit prediction webapp - https://www.transsee.ca/ I use GTFS-RT feeds from many transit agencies, as well as other APIs. For GTFS-RT I mostly use the Vehicle Position feed to calculate my own predictions based on the schedule and historical travel times because I found Trip Update predictions weren't as reliable.

Based on my needs and experience, here are my suggestions.

Include the route_id in the Trip Update, Vehicle Position and Alert feeds.

Include vehicles in the Vehicle Position feed if they deviate from their scheduled route, are operating on an unscheduled shuttle service or just include their location at all times even if they are out of service at the garage.

Include Trip Updates for at least an hour into the future, more if the service is infrequent.

**Comment by e-lo** [comment]
@barbeau are any of these addressed in v1.0? 

@doconnoronca if these are not addressed then you can refer to the current governance model for adding new suggestions in this repo's README.md - essentially you just need to translate this issue into a pull request.

**Comment by barbeau** [comment]
@e-lo A few notes below on inclusion in v1.0

>Include the route_id in the Trip Update, Vehicle Position and Alert feeds.

Not included in v1.0 - I'd be curious to hear more about why for each type of feed

>Include vehicles in the Vehicle Position feed if they deviate from their scheduled route, are operating on an unscheduled shuttle service or just include their location at all times even if they are out of service at the garage.

None of these cases are covered in v1.0.

IMHO generally speaking there needs to be more community discussion for what constitutes a best practice for inclusion of vehicles in a GTFS Realtime feed. There was a past discussion of this on Sept 23rd 2020 on MobilityData Slack at https://mobilitydata-io.slack.com/archives/C3NH9A9TQ/p1600885187000700 and I believe on the GTFS Realtime Google Group too (although I don't have a link handy for that).

I personally think "when deviating from scheduled route" makes sense.

"are operating on an unscheduled shuttle service" - Is this is referring to exact_times=0 frequency trips? Or is this referring to service that's not in the GTFS Schedule data?

"all all times even if they are out of service at the garage" - IIRC in the above Slack thread the tentative consensus there is that vehicles heading to start a trip should be assigned to the trip they are going to start and should appear in the feed, but vehicles that have finished a trip and heading to garage should not appear in feed. cc'ing @stevenmwhite (Syncromatics), @matikin9 (LA Metro), and @skyqrose (MBTA) on this as they had some good comments on practice in the Slack thread.

>Include Trip Updates for at least an hour into the future, more if the service is infrequent.

The [GTFS Realtime spec](https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/trip-updates.md) currently says:

>the feed should include a TripUpdate for the trip currently being served by the vehicle. Producers are encouraged to include TripUpdates for one or more trips after the current trip in this vehicle's block if the producer is confident in the quality of the predictions for these future trip(s). Including multiple TripUpdates for the same vehicle avoids prediction "pop-in" for riders as the vehicle transitions from one trip to another and also gives riders advance notice of delays that impact downstream trips (e.g., when the known delay exceeds planned layover times between trips).

See the proposal for this in PR https://github.com/google/transit/pull/206 for more discussion. Essentially it's a choice between providing potentially bad predictions vs providing no info at all - in that no info is better than bad info for some systems. Producers/consumers were hesitant to put an exact time window on a recommendation because of diversity of producers so we settled on the above text. I'm certainly open to further discussion on this topic if desired.

@doconnoronca As @e-lo says, please feel free to propose these via PRs! Please open one PR per topic and link to those here so we can keep the discussion focused - I replied with some preliminary comments above but it would be good to have subsequent discussions on each issue in separate threads. The "why" of the best practice is very important, so please be sure to include that rationale as well. When you open the pull request there is a template there to help guide this discussion (see preview [here](https://github.com/MobilityData/GTFS_Realtime_Best-Practices/blob/master/.github/PULL_REQUEST_TEMPLATE.md)).

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
