### ISSUE TITLE
Proposed best practice: including trip_id in TripDescriptor

### ISSUE THREAD

**Issue by emmambd** [MobilityData/GTFS_Realtime_Best-Practices#22]
[In the spec](https://gtfs.org/realtime/reference/#message-tripdescriptor), producers can identify trips by either 1) having a trip_id that corresponds to the trip_id in GTFS Schedule, or 2) by including all of `route_id`, `direction_id`, `start_date`, and `start_time` instead.

However, based on conversation in [#gtfs-realtime](https://mobilitydata-io.slack.com/archives/C3D321CKB/p1681827091229099) ([you can join the Slack here](https://share.mobilitydata.org/slack)), option 1 (using trip_id) is easiest and most commonly used by consumers. Option 2 causes headaches and sometimes isn't supported by consumers at all. As a result, it would make sense to recommend that producers use trip_id in all cases.

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
