### ISSUE TITLE
Add link to GTFS Resource and GTFS Realtime Specification

### ISSUE THREAD

**Issue by e-lo** [MobilityData/GTFS_Realtime_Best-Practices#9]
To increase discoverability and knowledge of the GTFS Realtime best practices as well a their perceived legitimacy, it would be very helpful to have links to this repository from [gtfs.mobilitydata.org](gtfs.mobilitydata.org) as well as [github.com/google/transit](github.com/google/transit).

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
